Updated Breadcrumb Template
softwareforgood/innocent_tech_app pull request #57
Opened 2024-04-03 17:32 UTC by AynAhmed

### Changes
Give a short summary of the changes made in this PR. 
Wrote logic and fixed bug of the breadcrumb feature. 

### Link to Issue 
Link Asana ticket here!
https://app.asana.com/0/1206510424537042/1206673931535429/f

### Comments, Notes, or  Questions
This section is if you want to share something related to the PR with the reviewer. 
(Rebased with the main and created a branch, to get rid of the readme commit)

### Related Screenshots 
For FE tickets specifcially, please include a screenshot of your work!

### Before you submit for review, Did you...

- [x] Added relevant tests (if applicable)
- [x] Linked Asana ticket to PR
- [x] Added comments, notes, or questions for reviewwer
- [ ] Added relevant screenshots
- [x] Ensured ticket title is clear and concise(i.e. 'Donation Form Feature' instead of 'sfg/chels/donation-form'

2024-04-03 20:00 UTC, edithemmings commented on app/views/layouts/application.html.erb
> +        <%= yield %>
Looks like you have yield in here twice now. How is the app looking when you run it locally?

2024-04-03 20:07 UTC, edithemmings commented on app/views/layouts/_navigation.html.erb
> +<% puts "Route list: #{nav_list}" %>
Are you using puts for debugging? Make sure to clean it up when you're done

2024-04-03 20:10 UTC, edithemmings reviewed
Do you have a screenshot of how it looks when you run it? Would be nice to see an example. Maybe with the students controller?

I tried to mess around with on my local setup and it was looking a little off
![Screenshot 2024-04-03 at 3 12 15 PM](https://github.com/softwareforgood/innocent_tech_app/assets/47989172/cf7589d6-a36b-4c2a-b203-876a8a9b7140)

2024-04-03 20:42 UTC, AynAhmed commented on app/views/layouts/_navigation.html.erb
> +<% puts "Route list: #{nav_list}" %>
Sorry, forgot you can't keep that in when you push. i'll clean it up and keep that in mind.

2024-04-03 20:43 UTC, AynAhmed commented
> Do you have a screenshot of how it looks when you run it? Would be nice to see an example. Maybe with the students controller?
> 
> I tried to mess around with on my local setup and it was looking a little off ![Screenshot 2024-04-03 at 3 12 15 PM](https://private-user-images.githubusercontent.com/47989172/319341037-cf7589d6-a36b-4c2a-b203-876a8a9b7140.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNzcwMTEsIm5iZiI6MTcxMjE3NjcxMSwicGF0aCI6Ii80Nzk4OTE3Mi8zMTkzNDEwMzctY2Y3NTg5ZDYtYTM2Yi00YzJhLWIyMDMtODc2YThhOWI3MTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDIwMzgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzYTJiY2MyYjg4MjkxODhiYWUyOWYxMjJkNDBhZDhjODk5OTE3OGNkN2I5NmFlZmMyMzE3MzUyODc3YTBiNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zotstmUtGqd1Zci4LNJSkfBMx4bhoARuzxtm8anHJBo)

2024-04-04 10:01 UTC, AynAhmed commented
screenshot

<img width="431" alt="Screenshot 2024-04-04 at 5 00 52 AM" src="https://github.com/softwareforgood/innocent_tech_app/assets/105397672/50402254-165d-4ea6-ad00-f86810dc89f5">


> Sorry, I was working on something else i noticed. But I can remake the routes and to show a screenshot of how it looks. but now that I see how you tested it I think I might have to add to it to account for how it handles routes with parameters. Because with how its set it will only track the route the user visited.
> 
> > Do you have a screenshot of how it looks when you run it? Would be nice to see an example. Maybe with the students controller?
> > I tried to mess around with on my local setup and it was looking a little off ![Screenshot 2024-04-03 at 3 12 15 PM](https://private-user-images.githubusercontent.com/47989172/319341037-cf7589d6-a36b-4c2a-b203-876a8a9b7140.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNzcwMTEsIm5iZiI6MTcxMjE3NjcxMSwicGF0aCI6Ii80Nzk4OTE3Mi8zMTkzNDEwMzctY2Y3NTg5ZDYtYTM2Yi00YzJhLWIyMDMtODc2YThhOWI3MTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDIwMzgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzYTJiY2MyYjg4MjkxODhiYWUyOWYxMjJkNDBhZDhjODk5OTE3OGNkN2I5NmFlZmMyMzE3MzUyODc3YTBiNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zotstmUtGqd1Zci4LNJSkfBMx4bhoARuzxtm8anHJBo)

2024-04-04 16:11 UTC, edithemmings commented
Are you able to make the list items appear inline like the screenshot in the ticket?

<img width="866" alt="Screen Shot 2024-02-22 at 4 07 10 PM" src="https://github.com/softwareforgood/innocent_tech_app/assets/47989172/189d47c2-ad11-4f17-a7eb-3299e8b0b64e">

2024-04-04 16:11 UTC, edithemmings commented on README.md
> -*Check-in: Are you  looking forward to writing tests?*
Extra space

2024-04-04 16:13 UTC, edithemmings commented on app/views/layouts/application.html.erb
> +        <div class="container main-content ml-64 mb-96 list-none">
This is the container for the entire screen (except for the sidebar). I'm hesitant to apply styles here that should only be for the navigation.

2024-04-04 16:14 UTC, edithemmings commented on app/views/layouts/application.html.erb
> +          <div  class= "mb-96>
Again, you're wrapping the `yield` in here, which will render the full content of every page. It also looks like you're missing a closing quotation

2024-04-09 14:41 UTC, camckin10 commented on README.md
> -*Check-in: Are you  looking forward to writing tests?*
Also it looks like you committed the onboarding readme

2024-04-11 08:12 UTC, AynAhmed commented
> Its looking good @AynAhmed !
> 
> 1)When I pulled down your branch and ran it locally, I got the following view: ![Screen Shot 2024-04-09 at 9 49 01 AM](https://private-user-images.githubusercontent.com/20117893/320894920-f1c000ca-b0a8-4715-8c1e-1951071b6811.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjMzNjgsIm5iZiI6MTcxMjgyMzA2OCwicGF0aCI6Ii8yMDExNzg5My8zMjA4OTQ5MjAtZjFjMDAwY2EtYjBhOC00NzE1LThjMWUtMTk1MTA3MWI2ODExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA4MTEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkYjk4M2MxZGYxNzU2NDIwOTY3MWZjMjA1N2EzMDIzZTA3NmQ4ZDE3NDQ4ZDczMmRlNzczYmQ2NWM1YjMwNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sPq2DWcE-WJLkEEj0svCklnqXWz-dZ7as7zfWf2-BNI) This looks great so far. Have you tried adding other links to see if the rest of the content appears inline?
> 
> Once you have tried that, can you please post a screenshot to this PR?

Sorry, I must of missed this but here is the screenshot: 
<img width="374" alt="Screenshot 2024-04-11 at 3 04 04 AM" src="https://github.com/softwareforgood/innocent_tech_app/assets/105397672/e77bdb73-5702-4ea1-b83e-e272f4d7eda7">

2024-04-11 20:52 UTC, edithemmings commented on app/views/layouts/application.html.erb
> +        <div class = "ml-96" >
I think it would look better without this class. Here's the comparison when I run it locally:
With the class:
<img width="1357" alt="Screenshot 2024-04-11 at 3 51 55 PM" src="https://github.com/softwareforgood/innocent_tech_app/assets/47989172/f7a4db8f-3c30-4159-812b-f27e095edf16">

Without the class:
<img width="1315" alt="Screenshot 2024-04-11 at 3 51 42 PM" src="https://github.com/softwareforgood/innocent_tech_app/assets/47989172/a36e5a60-487d-4f37-8784-5b320b129380">

2024-04-11 20:53 UTC, edithemmings reviewed
Love the use of a gem helper! Looks like a great solution. I left one comment about the layout. Also, please resolve your merge conflicts

2024-04-12 17:17 UTC, edithemmings reviewed
The PR is in draft status and it looks like rubocop is failing?

2024-04-12 18:14 UTC, AynAhmed commented on app/views/layouts/application.html.erb
> +        <div class = "ml-96" >
updated

2024-04-12 18:37 UTC, camckin10 commented
@AynAhmed  Please update your PR description with a screenshot of your local instance showing the breadcrumbs.

2024-04-12 18:39 UTC, camckin10 submitted a review, later dismissed
@AynAhmed  Looks good. Left a few comments to make on your PR. Before merging please:

- Update your PR to have a screenshot of what the breadcrumbs look like locally on your computer. 
- Resolve all of your conversations on this PR 
- Merge main into your branch (if needed)

2024-04-15 19:21 UTC, AynAhmed commented
done

2024-04-16 15:08 UTC, AynAhmed commented
fix

> > done
> 
> You still have conflicts @AynAhmed

fixed

2024-04-16 15:51 UTC, camckin10 submitted a review, later dismissed
👍  Nice! Nice clean up as well.

2024-04-16 16:42 UTC, camckin10 approved these changes
✅

2024-04-16 16:44 UTC, edithemmings requested changes
Looks like some things went awry during conflict resolving

2024-04-16 16:58 UTC, AynAhmed commented on app/views/students/index.html.erb
> +<h1 class="flex flex-wrap justify-center mx-auto py-8 px-4 md:mb-16"> HELLO INDEX!</h1>
ok will fixed

2024-04-16 17:23 UTC, AynAhmed commented
> Looks like some things went awry during conflict resolving

updated that

2024-04-16 18:24 UTC, edithemmings approved these changes
Looks great! Thanks for fixing that file

2024-04-16 18:26 UTC, merged