seeds data for ways-of-being form, controlle, routes,and edit file cr…
softwareforgood/innocent_tech_app pull request #96
Opened 2024-05-01 19:56 UTC by asmanoor17

…eated

### Changes
Give a short summary of the changes made in this PR. 

### Link to Issue 
Link Asana ticket here!

### Comments, Notes, or  Questions
This section is if you want to share something related to the PR with the reviewer. 

### Related Screenshots 
For FE tickets specifcially, please include a screenshot of your work!

### Before you submit for review, Did you...

- [ ] Added relevant tests (if applicable)
- [ ] Linked Asana ticket to PR
- [ ] Added comments, notes, or questions for reviewwer
- [ ] Added relevant screenshots
- [ ] Ensured ticket title is clear and concise(i.e. 'Donation Form Feature' instead of 'sfg/chels/donation-form'

2024-05-03 14:49 UTC, camckin10 commented
@asmanoor17  First review, it looks good.  
Update your PR description with the proper content such as the summary of changes, adding Asana ticket link, FE screenshot of the form,  and complete the checklist at the bottom of the description.

2024-05-03 15:02 UTC, camckin10 commented on config/routes.rb
>      resources :way_of_being
Double check the routes for this ticket. 
When I pull down your branch, and start the app locally, I get this error when I navigate to the 
http://localhost:3000/students/1/ways_of_being/edit url: 
![Screen Shot 2024-05-03 at 10 00 39 AM](https://github.com/softwareforgood/innocent_tech_app/assets/20117893/64263fb2-56cd-452a-bf6e-cc3e708de9e5)

2024-05-03 15:27 UTC, KNAthari requested changes

2024-05-03 15:27 UTC, KNAthari commented on config/routes.rb
>      resources :way_of_being
I was just about to say the same thing.

2024-05-03 15:27 UTC, KNAthari commented on app/views/ways_of_being/edit.html.erb
I see two view folders titled 'way of being' and 'ways of being' is that intentional?

2024-05-03 21:18 UTC, asmanoor17 commented on app/views/ways_of_being/edit.html.erb
yeah I moved over the code from creeds merge into main, we basically had to take the same steps to work on our tickets! (:

2024-05-06 20:34 UTC, asmanoor17 commented
<img width="1440" alt="Screenshot 2024-05-06 at 3 34 01 PM" src="https://github.com/softwareforgood/innocent_tech_app/assets/143779110/79b0d744-174f-49db-b1f4-0ec8bba00b5c">

2024-05-07 14:29 UTC, edithemmings commented on app/views/ways_of_being/show.html.erb
> +<button onclick="window.location.reload();" class="btn btn-secondary">Refresh</button>
Did a quick google to see if there was a "Railsier" way. Looks like there's a pretty simple one:
https://stackoverflow.com/questions/18760253/how-to-create-simple-refresh-page-link-with-ruby-on-rails

2024-05-07 14:41 UTC, camckin10 commented
> <img alt="Screenshot 2024-05-06 at 3 34 01 PM" width="1440" src="https://private-user-images.githubusercontent.com/143779110/328310982-79b0d744-174f-49db-b1f4-0ec8bba00b5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwOTMwNjgsIm5iZiI6MTcxNTA5Mjc2OCwicGF0aCI6Ii8xNDM3NzkxMTAvMzI4MzEwOTgyLTc5YjBkNzQ0LTE3NGYtNDlkYi1iMWY0LTBlYzhiYmEwMGI1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QxNDM5MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNzQ3NTI4MmU3ZmNmZGYwYTEzZmFlODNlNzllZjk1ZDUyZDE5ZjI1YWJmYzVjY2MzNTUyNDZiZGY4NzcwODcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HrUBlDPX5Txntiy6L6vQH9j7BdYECepaqQN0FxBF1T4">

@asmanoor17  If this screenshot is the most updated local view, You can remove this comment, and instead replace the image you uploaded in this comment into the initial PR description box.

2024-05-07 15:41 UTC, asmanoor17 commented on app/views/ways_of_being/show.html.erb
> +<button onclick="window.location.reload();" class="btn btn-secondary">Refresh</button>
this is what I'm seeing `link_to "reload", url_for(params)` so what would go in the `(params)` part?

2024-05-07 18:40 UTC, edithemmings commented on app/controllers/ways_of_being_controller.rb
> +class WaysOfBeingController < ApplicationController
Nice work refactoring/correcting the naming!

2024-05-07 18:44 UTC, edithemmings commented on app/controllers/ways_of_being_controller.rb
> +    @student = Student.find(params[:student_id])
When the same line of code is run at the beginning of multiple controller actions, it's a great opportunity to use a `before_action`
This enables you to write this repeated code in just 1 method, and then make it so it runs before every action. 
https://guides.rubyonrails.org/action_controller_overview.html#filters

2024-05-07 18:46 UTC, edithemmings commented on app/controllers/ways_of_being_controller.rb
> +    @student = Student.find(params[:student_id])
Something like
```ruby
class WaysOfBeingController < ApplicationController
  before_action :set_student
  ...
  private
  ...
  def set_student
    @student = Student.find(params[:student_id])
  end
end
```

2024-05-07 18:51 UTC, edithemmings commented on app/views/ways_of_being/show.html.erb
> +<%= link_to "Continue",controller_path, class: "btn btn-primary" %>
^Are these two buttons working for you locally? I'm seeing some odd behavior when I pull down the code

2024-05-07 18:53 UTC, edithemmings commented on app/views/ways_of_being/show.html.erb
Why have a show page and an edit page? Did you mean to remove one of them? I'm not sure these are working how rails expects. A way of being show would usually be for displaying a single way of being

2024-05-07 18:56 UTC, edithemmings commented on app/views/ways_of_being/edit.html.erb
> +    <% @ways_of_being.first(4).each do |ways_of_being| %>
this line is causing an error for me because `@ways_of_being` is not defined in your `edit` controller action
http://localhost:3000/students/1/ways_of_being/1/edit
<img width="1128" alt="Screenshot 2024-05-07 at 1 55 53 PM" src="https://github.com/softwareforgood/innocent_tech_app/assets/47989172/53b6c5fd-9424-4dc7-8856-9632dfee45e1">

2024-05-07 19:04 UTC, edithemmings reviewed
I think you might be having some confusion between show and edit. 
Your show url is:
http://localhost:3000/students/{student_id}/ways_of_being/{way_of_being_id}
(rails expects you to be viewing a single way of being)

And your edit url is:
http://localhost:3000/students/{student_id}/ways_of_being/{way_of_being_id}/edit
(rails expects you to be editing a single way of being)

But I think when we paired you were passing in "edit" as the way_of_being_id into the _show_ route. 
This entire feature design is a little goofy because it doesn't adhere to rails standards: Technically the single entity we are editing is student, but there are a ton of other forms where we're editing the student entity, so we can't just do http://localhost:3000/students/{student_id}/edit, or we'd have too much overlap. 

In the future it might make sense to have a custom action. For now, since this is so close. I am fine with keeping the "show" action and passing in "edit" as the ID, and then cleaning up all the edit stuff. But just know that this might need to change if we build on it in the future

2024-05-08 06:12 UTC, fouziiah commented on config/routes.rb
> +    resource :ways_of_being, only: [:edit, :update], controller: 'ways_of_being'
Suggestion: since rails uses convention-over-configuration principle, specifying the controller name in the routes file might be redundant. Rails typically infers the controller based on the resource name. It maintains the consistency of rails conventions.

2024-05-09 19:40 UTC, edithemmings commented on config/routes.rb
> +    resource :ways_of_being, only: [:edit, :update], controller: 'ways_of_being'
^YES! And if you were having some trouble with rails inferring the controller, it might be because you need to pluralize `resource` -> `resources`

2024-05-10 14:16 UTC, edithemmings reviewed
Left some comments, but we'll go through it all when we pair this morning

2024-05-13 14:48 UTC, edithemmings commented on app/controllers/ways_of_being_controller.rb
> +    @ways_of_being = @student.ways_of_being
We want to see all of the ways of being (even if they don't belong to the student yet). So that we can add new ones to the student if we want to

2024-05-13 14:49 UTC, edithemmings commented on app/views/ways_of_being/form.html.erb
This looks good, but isn't doing what the ticket is asking for. We just want a multi-select form (with NO styling) that allows us to add new ways of being to the student

2024-05-13 17:03 UTC, asmanoor17 commented on app/controllers/ways_of_being_controller.rb
> +    @ways_of_being = @student.ways_of_being
so have this instead?:   
    def form
    @student = Student.find(params[:student_id])
    @ways_of_being = WayOfBeing.all
  end

2024-05-13 17:04 UTC, asmanoor17 commented on app/views/ways_of_being/form.html.erb
This is what I currently have, is this doing what the ticket is asking for? 

<body>
  <div>
    <div>
      <h1>Add New Ways of Being for <%= @student.first_name %></h1>
    </div>
  </div>
  <% if @ways_of_being.present? %>
    <form action="<%=  new_student_way_of_being_path %>" method="post">
      <select multiple name="new_ways_of_being[]">
        <% @ways_of_being.each do |ways_of_being| %>
          <option value="<%= ways_of_being.id %>"><%= ways_of_being.name %></option>
        <% end %>
      </select>
      <button type="submit">Add Selected Ways of Being</button>
    </form>
  <% else %>
    <p>No ways of being found.</p>
  <% end %>
</body>
<%= link_to "Go Back",student_ways_of_being_path(@student), class: "btn btn-primary" %>
<%= link_to "Continue",student_path(@student), class: "btn btn-primary" %>
<%= link_to "Refresh", url_for(request.params), class: "btn btn-secondary" %>

2024-05-13 17:51 UTC, edithemmings commented on app/controllers/ways_of_being_controller.rb
> +    @ways_of_being = @student.ways_of_being
Yep!

2024-05-13 17:54 UTC, edithemmings commented on app/views/ways_of_being/form.html.erb
If you have updates to the code, please push them for the convenience of the reviewer. It looks like you're headed in the right direction, but you're using literal html elements instead of the railsier form helpers.... Is the form working when you submit it?

2024-05-17 18:26 UTC, edithemmings commented on app/controllers/ways_of_being_controller.rb
> +  def wayofbeing_form
I think rubocop just wants you to clean up this method a little. Maybe start by taking out all those debug logs

2024-05-20 19:06 UTC, KNAthari reviewed
So, the form looks alright. However, some ways of being are missing on my end (I don't know if you added any more on your end), and is the spacing between the different ways of being intentional?

2024-05-21 13:51 UTC, edithemmings reviewed
Left a few comments for cleaning up code and making sure you're using the right route for the form submission

2024-05-21 13:51 UTC, edithemmings commented on app/controllers/ways_of_being_controller.rb
> +  def update
^Is this still being used? I think you can clean it up

2024-05-21 13:51 UTC, edithemmings commented on app/controllers/ways_of_being_controller.rb
> +  def set_way_of_being
^I don't see this being used. You can remove

2024-05-21 13:51 UTC, edithemmings commented on app/controllers/ways_of_being_controller.rb
> +  def ways_of_being_params
If you take out `update` this can go too

2024-05-21 13:51 UTC, edithemmings commented on config/routes.rb
>      resources :way_of_being
I don't think we need the singular route anymore

2024-05-21 13:51 UTC, edithemmings commented on app/views/ways_of_being/form.html.erb
> +<%= form_with url: student_ways_of_being_path(student_id: @student.id), method: :get do |form| %>
^It doesn't save when I try to run it locally. I think you want this to be hitting your `wayofbeing_form` route.

2024-05-21 16:05 UTC, asmanoor17 commented on app/views/ways_of_being/form.html.erb
> +<%= form_with url: student_ways_of_being_path(student_id: @student.id), method: :get do |form| %>
when I do the `waysofbeing_form` route it seems like its only refreshing the page? and this is how the url looks after saving: [(http://localhost:3000/students/1/ways_of_being/form?id%5B1%5D=&way_of_being_ids%5B%5D=&way_of_being_ids%5B%5D=18&way_of_being_ids%5B%5D=9&commit=Add+Selected+Ways+of+Being)]

2024-05-21 18:36 UTC, edithemmings commented on app/views/ways_of_being/form.html.erb
> +<%= form_with url: student_ways_of_being_path(student_id: @student.id), method: :get do |form| %>
Hmm that is what it appears to be doing now. Could you push the example of when you do `waysofbeing_form`?

2024-05-21 18:36 UTC, edithemmings commented on app/controllers/ways_of_being_controller.rb
> +  def update
going to keep these comments unresolved until I see the fixes come through

2024-05-21 21:00 UTC, edithemmings commented on app/views/ways_of_being/form.html.erb
> +<%= form_with url: form_student_ways_of_being_path(student_id: @student.id), method: :get do |form| %>
This looks like its going to the `form` route, when I think you want the `waysofbeing_form` route? Maybe naming `waysofbeing_form` to something else might help with this?

2024-05-21 21:02 UTC, edithemmings commented on config/routes.rb
> -      post :wayofbeing_form, on: :collection
^Wait this is the one you want to be calling on form submit!!

2024-05-23 14:22 UTC, edithemmings approved these changes
Looks great Asma!!! Great job working through some difficult overrides/customizations!

2024-05-23 16:07 UTC, crestu approved these changes
Looks good! Everything working well

2024-05-23 16:21 UTC, merged